language: php

php:
  - "5.7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml


after_script:
  - php vendor/bin/coveralls -v
